title: SG Internship Listing
remote_theme: pages-themes/architect@v0.2.0

repository: eaziym/sg-internship-listing
markdown: kramdown

description: A curated list of internship opportunities in Singapore for students and fresh graduates.

plugins:
  - jemoji
  - jekyll-remote-theme

# Add viewport meta tag for mobile responsiveness
webmaster_verifications:
  google: null
  bing: null
  alexa: null
  yandex: null
  baidu: null

# Ensure proper mobile rendering
defaults:
  - scope:
      path: ""
    values:
      layout: default
